version: "3.9"

services:
    express:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: .
              target: /app

            - type: volume
              target: /app/node_modules
        ports:
            - "5000:5000"
            - "9229:9229"
        command:
            - nodemon
            - -L
            - --inspect=0.0.0.0:9229
            - server.js
