version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./backed:/app/backend
        ports:
            - "5000:5000"
